"""add invited_by to User, contact_user_id to Contact

Revision ID: 1e3b7e7fa259
Revises: 3e8383d36521
Create Date: 2021-11-26 18:39:05.666313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3b7e7fa259'
down_revision = '3e8383d36521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('contact_user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'contacts', ['contact_user_id'])
    op.add_column('users', sa.Column('invited_by', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['invited_by'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'invited_by')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'contact_user_id')
    # ### end Alembic commands ###
