"""fix User's invited_by constraint

Revision ID: 508756c1b8b3
Revises: edba592acd36
Create Date: 2021-11-26 19:59:35.589268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508756c1b8b3'
down_revision = 'edba592acd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_invited_by_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_invited_by_key', 'users', ['invited_by'])
    # ### end Alembic commands ###
