"""change push-subscriptions relation

Revision ID: 98c5ae7802f8
Revises: 87c56464f8a8
Create Date: 2021-11-18 17:59:59.158785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c5ae7802f8'
down_revision = '87c56464f8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('push_subscriptions_contact_id_fkey', 'push_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'push_subscriptions', 'users', ['user_id'], ['id'])
    op.drop_column('push_subscriptions', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'push_subscriptions', type_='foreignkey')
    op.create_foreign_key('push_subscriptions_contact_id_fkey', 'push_subscriptions', 'contacts', ['contact_id'], ['id'])
    op.drop_column('push_subscriptions', 'user_id')
    # ### end Alembic commands ###
