"""cascade delete for push_sub

Revision ID: d6848c3b8e33
Revises: d7084539f84b
Create Date: 2021-12-26 19:13:58.629405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6848c3b8e33'
down_revision = 'd7084539f84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
