"""add created_at field to push_subscription

Revision ID: d7084539f84b
Revises: ece365464f74
Create Date: 2021-12-26 13:27:33.300902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7084539f84b'
down_revision = 'ece365464f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_subscriptions', 'created_at')
    # ### end Alembic commands ###
