"""fix user agent relationship

Revision ID: ece365464f74
Revises: bcc01ca59789
Create Date: 2021-12-26 12:41:26.168088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece365464f74'
down_revision = 'bcc01ca59789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
